### ISSUE TITLE
test beta version

### ISSUE THREAD

**Issue by mirkokrajco** [litinoveweedle/SmartIR#102]
**Home Assistant version**
 Core 2024.7.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

**SmartIR version**
1.18b3

**SmartIR configuration**

climate:
  - platform: smartir
    name: Obyvačka klima
    unique_id: obyvacka_klima
    device_code: 1281
    controller_data:
      controller_type: MQTT
      mqtt_topic: zigbee2mqtt/Dialkove ovladanie 1/set
    temperature_sensor: sensor.teplota_obyvacka_temperature
    humidity_sensor: sensor.teplota_obyvacka_humidity

  - platform: smartir
    name: Spálňa klima
    unique_id: spalna_klima
    device_code: 1281
    controller_data:
      controller_type: MQTT
      mqtt_topic: zigbee2mqtt/Dialkove ovladanie 2/set

**Describe the bug**

Error in log file:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/smartir/climate.py", line 90, in async_setup_platform
    async_add_entities([SmartIRClimate(hass, config, device_data)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartir/climate.py", line 224, in __init__
    self._controller = get_controller(
                       ^^^^^^^^^^^^^^^
  File "/config/custom_components/smartir/controller.py", line 49, in get_controller
    raise Exception(
Exception: Configured controller is not supported by the device data file.

**Comment by litinoveweedle** [comment]
The error says all:

`Configured controller is not supported by the device data file.`

You choose JSON file, which is not suitable for your IR remote.
