### ISSUE TITLE
Can we get an icon for SmartIr?

### ISSUE THREAD

**Issue by adimosh** [litinoveweedle/SmartIR#109]
**Is your feature request related to a problem? Please describe.**
Currently, SmartIr does not have a recognizable icon.

**Describe the solution you'd like**
I would like for SmartIR to have an icon, so that the entities created by it also have icons.

**Describe alternatives you've considered**
N/A

**Additional context**
The latest Home Assistant tries its best to show all integrations, devices and entities, regardless of whether or not they've been added through YAML. Because of this, SmartIR shows up as empty in the Integrations page, and entities just take the default icon for their type (climate, for example has a strange-looking dial thingy). It would really help if this integration had a usable icon.

**Comment by litinoveweedle** [comment]
It is not completely clear which icon you mean, but if you means entity icon, then:

1. user can freely change the icon in the entity list
2. current default icon is based on the integration class (climate, fan, media_player), so for example for SmartIR climate entity the default one (the one you describe as 'strange-looking dial thingy') is `mdi-thermostat` and it is Home Assistant default
3. as written in the [HomeAssistant documentation](https://developers.home-assistant.io/docs/core/entity#icons): .... 
_In most cases, Home Assistant will pick an icon automatically based on the entity's domain, device_class, and state. It is preferred to use the default icon if possible, to provide a consistent experience and to avoid confusion for the user._

So based on the above, what exactly you would like to achive?

**Comment by adimosh** [comment]
![image](https://github.com/user-attachments/assets/64f97ccf-3424-4944-810f-8731a8d19fe7)

This is what I'm talking about.

**Comment by litinoveweedle** [comment]
Ahhh ok,  now I understand. Unfortunately, this icon is not up to the integration to set/define/use. Those brand icons are kept and maintained as part of the HA project [brands repo](https://github.com/home-assistant/brands). There is not to much I can or I would like to do - just see the requirements and long PR list - I have neither the time nor the patience to spend just for the icon to show. But if you would prepare such PR I can push it for SmartIR.

**Comment by litinoveweedle** [comment]
PR requested but not delivered, therefore I am closing this for now. Please feel free to reopen this once you push mentioned PR.
