### ISSUE TITLE
device_class in media_players (documentation)

### ISSUE THREAD

**Issue by charliejgallo** [litinoveweedle/SmartIR#112]
tried setting the device_class in media_player and works well!! didn't see that in the documentation...

just added the device_class (could be set as tv, receiver or speaker) and the interface shows the updated icon...
if device_class is not set it defaults as "TV"

sorry couldn't place the "documentation" label....

thanks for everything!!

(mqtt IR Zs06 with zigbee2mqtt, smartir 1.18)

<img width="558" alt="Screen Shot 2024-08-18 at 13 06 03" src="https://github.com/user-attachments/assets/8ab10312-28d0-44c9-a317-ec1c94d5464f">
<img width="377" alt="Screen Shot 2024-08-18 at 13 05 40" src="https://github.com/user-attachments/assets/b3d642f4-71cf-49e7-a0bf-4f130db64501">

**Comment by litinoveweedle** [comment]
Hello, thank you very much for the finding, I will add your finding into documentation.
