### ISSUE TITLE
Unable to send triple command

### ISSUE THREAD

**Issue by Den1s39** [litinoveweedle/SmartIR#120]
In the old version from smartHomeHub I could send a double/triple command like
`
      "3": [
        "JgAsAFceDx0ODw4PDh0eDg4PDg8ODw4PDg8MEA0QDRAPDg8ODw4PDg8ODw4dAA0F",
        "JgAsAFceDx0ODw4PDh0eDg4PDg8ODw4PDg8MEA0QDRAPDg8ODw4PDg8ODw4dAA0F",
		"JgAoAFUgDR4NEA0QKi4MEQwQDRANEA0QDRANEA0QDRANEA0QGx8NEBsADQU="
      ],
`
It doesn't work in your version.
Could you fix this?

**Comment by litinoveweedle** [comment]
Hello, as you did not considered filling the issue template I do not consider it is worthy to work on this. Closing as invalid. BTW I did checked original climate.py implementation and I do not see any functionality you refer to. If you want to reopen this you will need not only to correctly fill issue template but also find and point to the implementation you refer to in the original SmartIR.
