### ISSUE TITLE
Add codes for Della Portable AC 014-APAC-14 (and possibly others)

### ISSUE THREAD

**Issue by spikked27** [litinoveweedle/SmartIR#124]
**Is your feature request related to a problem? Please describe.**
Couldn't create a PR because I'm not a contributor

**Describe the solution you'd like**
JSON for Della brand portable AC attached

[2788.json](https://github.com/user-attachments/files/16853794/2788.json)

**Comment by litinoveweedle** [comment]
> Couldn't create a PR because I'm not a contributor

Hello, there is nothing preventing you from the:

1. fork repository.
2. modify (add file).
3. create Push Request.

could you please consider it?
