### ISSUE TITLE
I've created a json for Electrolux EXP35U538CW

### ISSUE THREAD

**Issue by BeardElk** [litinoveweedle/SmartIR#126]
Fully working and validated json for EXP35U538CW. 
Please add to normal config! 
[EXP35U538CW.json](https://github.com/user-attachments/files/16879837/EXP35U538CW.json)

**Comment by litinoveweedle** [comment]
Hello, thank you for the contribution. Would you please consider using standard approach? The flow shall be:

1. fork my repo
2. modify/add files i your repo
3. raise PR.

I hope this would be not complicated to do and would simplify my work a bit. Also it would add your name as a contributor to this project. ;-)

**Comment by Stromboli94** [comment]
There may have been some confusion, since the project this one is forked from originally stated that the way to add supported devices was to create an issue with the file as an attachment. IMO the PR approach is much cleaner.

**Comment by BeardElk** [comment]
> Hello, thank you for the contribution. Would you please consider using standard approach? The flow shall be:
> 
>     1. fork my repo
> 
>     2. modify/add files i your repo
> 
>     3. raise PR.
> 
> 
> I hope this would be not complicated to do and would simplify my work a bit. Also it would add your name as a contributor to this project. ;-)

I'll get right on it! 
Or try at least! Never done anything like it but, google is my friend!
