### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by neo2angel** [litinoveweedle/SmartIR#129]
Hello everyone,

First of all, please forgive my English, Mr. Google

I have installed smartir in version 1.17.9 and it works perfectly, but as I got warning messages, I decided to update to 18.

When I install it, I get two error messages:

"The 'smartir' integration does not support YAML setup, please remove it from your configuration"

"Setup failed for custom integration 'smartir': No setup or config entry setup function defined."

I have tried to follow the documentation, but I don't understand it

Could someone tell me step by step how to configure?

where to put the yaml/configuration?

The one I have now (and it worked in 1.17) is like this:

- platform: smartir
  name: CLIMATE - Aire Despacho
  unique_id: aire_despacho
  device_code: 1763
  controller_data: remote.despacho_ir_despacho_remote
  temperature_sensor: sensor.temperatura_despacho_correctida
  humidity_sensor: sensor.despacho_purificador_humidity

Thank you very much

**Comment by neo2angel** [comment]
If I write the message before, I find the solution sooner, I write it in case it helps someone

in version 1.17.9 in the configuration.yaml I had these lines

smartir:
force_update = false

if you have those lines, delete them, because it gives an error

**Comment by litinoveweedle** [comment]
You migrated between two different project, not just versions! 

```
smartir:
force_update = false
```

This configuration is not used for this project for long time.

You  did not read warning about breaking changes (from original project) and also not followed published configuration. examples published for this project. Closing this issue as invalid.
