### ISSUE TITLE
custom not starting

### ISSUE THREAD

**Issue by tayanov** [litinoveweedle/SmartIR#13]
if i try setup Yaml version, ha  say yaml not supported. Try GUI version.
if i try setup GUI version? ha say you need use Yaml.
wtf?

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by tayanov** [comment]
![Снимок экрана 2024-05-27 152756](https://github.com/litinoveweedle/SmartIR/assets/9577027/7ccbd02d-7ca1-4d4b-a7b5-097c0c176301)

**Comment by tayanov** [comment]
and more ...
Регистратор: homeassistant.helpers.entity
Источник: helpers/entity.py:1632
Первое сообщение: 15:24:57 (1 сообщений)
Последнее сообщение: 15:24:57

Entity None (<class 'custom_components.smartir.media_player.SmartIRMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|PLAY_MEDIA|VOLUME_STEP|SELECT_SOURCE: 4024>, please create a bug report at https://github.com/litinoveweedle/SmartIR/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by gianlucasullazzo** [comment]
Hi, same here. But it's working

**Comment by openg12** [comment]
to fix "the smartir  integration does not support YAML"  just delete the " smartir: " in configuration.yaml and then restart the HA

**Comment by gianlucasullazzo** [comment]
It works thanks

**Comment by litinoveweedle** [comment]
Hello,

this is intended behavior and not a bug, ;-) Please just delete line `smartir:` from your yaml configuration - as correctly noted by @openg12. This configuration is not needed anymore.
