### ISSUE TITLE
No description on HACS page

### ISSUE THREAD

**Issue by icefest** [litinoveweedle/SmartIR#136]
**Home Assistant version**
![image](https://github.com/user-attachments/assets/7d816159-42a4-478f-bb99-255c5ae3952f)

**SmartIR version**
![image](https://github.com/user-attachments/assets/29da20a9-e1bc-4ff5-92e5-a958414c402f)

**SmartIR configuration**
N/A
```yaml

Add SmartIR relevant part of HA configuration.yaml  formatted as a code here

```

**Describe the bug**
No INFO/README text when opening HACS SmartIR page
![image](https://github.com/user-attachments/assets/26981665-2701-44d4-af3d-6bf31047f03c)

**Expected behavior**
To see the full readme from github: (after editing `hacs.json` and renaming `INFO.md` to `README.md`)
![image](https://github.com/user-attachments/assets/2fc79230-4562-4f09-bc0c-8d337bbcef45)

**To Reproduce**
1. Go to 'HACS'
2. Click on 'SmartIR'
3. See error

**Debug log**
N/A

```

I'll put in pull request?

**Comment by litinoveweedle** [comment]
Hello, thank you for catching the issue and solving it as well. Your PR was merged into master.
