### ISSUE TITLE
MEDIA_TYPE_CHANNEL was used from smartir, this is a deprecated constant 

### ISSUE THREAD

**Issue by Claudio1L** [litinoveweedle/SmartIR#143]
deprecation message:

MEDIA_TYPE_CHANNEL was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.CHANNEL instead, please report it to the author of the 'smartir' custom integration

**Home Assistant version**
2024.10.1
**SmartIR version**
1.18.0
**SmartIR configuration**

**Describe the bug**
deprecation message:

MEDIA_TYPE_CHANNEL was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.CHANNEL instead, please report it to the author of the 'smartir' custom integration

**Expected behavior**
fix deprecation

**Comment by litinoveweedle** [comment]
Hello, thank you for report. I believe the fix is provided in #145 and was merger into master and is release in the [latest beta](https://github.com/litinoveweedle/SmartIR/releases/tag/1.19.0b2). Please test and report back. Thank you

**Comment by litinoveweedle** [comment]
I believe this is fixed now, closing the issue. Feel free to reopen it if not.
