### ISSUE TITLE
Sending commands to the HA Remote instead of codes

### ISSUE THREAD

**Issue by etique57** [litinoveweedle/SmartIR#146]
**Is your feature request related to a problem? Please describe.**
Hello,

A few years back, when automating my ceiling fans (I have 4 of the same manufacturer/model), I struggled a bit with the original SmartIR implementation (with the "code files"), as the only way I had available was to learn the codes through the remote service/command, and then create 1 file per fan. 

**Describe the solution you'd like**
I felt it a bit redundant compared to the existing Fan Service in HA, which already is able to pass "commands" to the devices. SmartIR was handy to create the fan entity automatically, but I didn't understand why I couldn't simply use the HA Remote commands.

I did a few modifications in the code, adding modifications in two files (here compared to smartir 1.17.9):

in fan.py:
![image](https://github.com/user-attachments/assets/faffd2cd-1d46-4805-ac3f-7cff6de9a5e8)

in controller.py (there's a bit more but the bulk is here):
![image](https://github.com/user-attachments/assets/c7830f5c-39dd-4979-a645-d0fef75214ad)

Configuration is then very simple, which is was I aiming at:
- the learn service generate the file with the proper commands and codes
- smartIR device file maps command names to HA remote names and generate the target device
![image](https://github.com/user-attachments/assets/af647f96-811c-400c-aa4b-4a7bdb872884)

**Describe alternatives you've considered**
As I'm willing to move to you updated implementation, I was considering doing a PR with my modifications... but I can't make it work. (I'm no developer, just a tinkerer)

If you think that's interesting, I can provide you with the files!

**Comment by litinoveweedle** [comment]
Hello,

I understand your approach, but this would bring breaking change to all current SmartIR users, where they would not be able to use existing device files anymore. And everyone would need to create (using learn command) their own codes from scratch, so no device codes sharing. I think that this will not be welcome by anyone. Also while this would work for controllers entity, there are also service based controllers like ZHA, or MQTT based controllers, which will not be supported by this implementation.

I understand, that learning commands is complex task and in the long term I would like to make it easier, but I don't think, that you proposal is going in the right direction.
