### ISSUE TITLE
Installation and Configuration problem

### ISSUE THREAD

**Issue by Gobolin80** [litinoveweedle/SmartIR#158]
**Home Assistant version**
2024.11.2

**SmartIR version**
1.19.0

Hi,
I tried to install this fork but was unsuccessful. Specifically, I:

1. Removed the original installation.
2. Added this custom repo to HACS.
3. Installed the component from this repo.
4. At this point, I restarted, and an error appeared telling me to remove the "smartir" configuration from the configuration.yaml file.
5. I did that and restarted.
6. Afterward, when attempting to add the integration, I received a message saying, "It is not possible to add this integration from the interface."

In practice, there was no way to add it either via YAML or via interface.
I restored the original SmartIR component, but even that no longer worked (same error).

I had to restore a backup to get the environment working again.

Are there some mistake in my process?

Thank you

**Comment by NzKyle** [comment]
I had the same. 

Remove the `smartir:` entry from your config file - that should fix the issue.

**Comment by litinoveweedle** [comment]
Thank you @NzKyle for providing help. I am currently travelling and I was not able to react myself.

**Comment by Gobolin80** [comment]
Hi @NzKyle and thank fou your reply.
As I mentioned in my initial post, I removed the 'smartir' tag, but I could no longer see the custom component into the integrations list.
I'll try again as soon as Ipossible.

Thanks

**Comment by MonsterVic** [comment]
I'm having exactly the same issue. I have also tried to move away from the original Smartir integration due to the lot of deprecated function and ran into the same problem as Gobolin80

**Comment by MonsterVic** [comment]
Hmm wait I just solved it somehow: 

This was the code in the original version: 

`smartir:    
  - platform: smartir
    name: Háló AC
    unique_id: halo_ac
    device_code: 9070
    controller_data: "zigbee2mqtt/InfraHalo/set/ir_code_to_send"`

And this now the working code without having the smartir:  at the beginning: 

` - platform: smartir
    name: Háló AC
    unique_id: halo_ac
    device_code: 9070
    controller_data: 
      controller_type: MQTT
      mqtt_topic: "zigbee2mqtt/InfraHalo/set/ir_code_to_send"`

**Comment by Tamsy** [comment]
> but I could no longer see the custom component into the integrations list.

Make sure to not to use the codes from the original Smartir integration but use the codes coming with litinoveweedle's fork .

If you have to bring old codes over make sure to save them into ../smartir/custom_codes/climate and add the line:

`  "temperatureUnit": "C",`

after the line `"commandsEncoding": "Base64",` to those json-files. Some of the old codes work with the above addition, other don't.

**Comment by litinoveweedle** [comment]
I added some information about potential migration issues from the original SmartIR into Readme file. I am closing this issue now.

**Comment by Gobolin80** [comment]
> Make sure to not to use the codes from the original Smartir integration but use the codes coming with litinoveweedle's fork .

I didn't know this!
I used my previously codes.
Thank you so much @Tamsy !

And thanks @litinoveweedle for you work

**Comment by Gobolin80** [comment]
ok,
now it work. It's all ok!

I did:

1. Unistall old version of smartir and restarted
2. Install smartir from this repo
3. Remove **smartir:** configuration entry in Configuration.yaml
4. Modify old climate configuration with new version of **controller_data** like described in the doc
5. Restart

Thanks all!
