### ISSUE TITLE
missing codes

### ISSUE THREAD

**Issue by trancer86** [litinoveweedle/SmartIR#159]
Hello. Thanks for supporting this integration. Can you tell me about the 1124.json codes are invalid? I used these codes to control my Mitsubishi Electric MSZ-FH35VE they worked for me. Now I can't use them. I'm a newbie and it's very hard for me to learn my own codes. I've been looking for a solution to this problem.

**Comment by litinoveweedle** [comment]
Enable debug logging and try to use mentioned code file. You will get more information about what is the problem from the logs. It should be solvable for you, especially if you have given device to experiment with. I will gladly accept PR for fixed code file. Closing this for now.
