### ISSUE TITLE
Add Support for That Midea Remote Everyone Has (RG10F2(D2)/BGEFU1)

### ISSUE THREAD

**Issue by geirskogul** [litinoveweedle/SmartIR#164]
I'm not too up on github, but I'm an HVAC tech that watches coding videos on lunch, and spent a weekend pulling and cross-referencing codes using my Broadlink RM4 mini with a half-dozen Midea (and MrCool and Carrier lower-end stuff, all made by midea) remotes and units, and have a unified config that applies to many units.  

However, I'm not up on github, and learning how to do a pull request and format it properly would be one thing, and when I was done with everything, I learned of this branch that some people are using.

Reading comments and descriptions, it seems like it would be even more work to translate this over here, and I simply don't have it in the cards for me.  But I do have a json that works with a ton of models of things.  Is it okay to share the working file here?

Remote Models this works for:
Midea RG10F2(D2)/BGEFU1
Midea RG10B(B)/BGEF
Midea/Dreo RG10B(K1)/BGEFU1

Tested climate models this works for:
Dreo TwinCool 12000 BTU Smart Inverter Portable Air Conditioner
Midea  8,000BTU, U-Shaped AC
Midea 12,000 BTU U-Shaped AC
Midea 10,000 BTU U-shaped AC
MRCOOL Versa Pro 30,000 BTU 2.5-Ton 16.5 SEER2 Central Ducted Heat Pump Split System MVP-30-HP-230-25
MRCOOL Versa Pro 30,000 BTU 3-Ton 16.5 SEER2 Central Ducted Heat Pump Split System MVP-36-HP-230-25
MRCOOL EZ Pro Single Zone 24000-BTU 18 SEER Ductless Mini Split EZPRO-24-HP-23016
MRCOOL EZ Pro Single Zone 12000-BTU 18 SEER Ductless Mini Split EZPRO-12-HP-11516

I've confirmed functionality of all commands with all devices.  There were many duplicated or incompatible commands that would cause issues across sub-models (where, say, 24c fan high recorded with one remote would activate auxiliary heat on another unit), but I used a hefty dose of claude, an excel spreadsheet, and a full workday of time to parse out and sanitize these IR commands to not cause any issues.    That said, troubleshooting the format of the yaml/json was almost more difficult for me.

I don't know the numbering scheme of the old or this new fork, but I called it 1832:

[1832.json](https://github.com/user-attachments/files/18163266/1832.json)

**Comment by litinoveweedle** [comment]
Hello, thank you fro your contribution. I did slightly modified your file to conform with improved structure of the climate JSON in this  project and merge it as #172
