### ISSUE TITLE
Code Format Conversion

### ISSUE THREAD

**Issue by gianlucasullazzo** [litinoveweedle/SmartIR#28]
Hi all,
This is not an issue but a simple help request. Do you know how to convert from ufo (zigbee) code format to broadlink code format?

**Comment by litinoveweedle** [comment]
Hello, sorry, but I do not know. I think I saw somewhere script, which was able to do a conversion, but I think it was in oposite direction (from broadlink to zigbee). 

OK , just [found it](https://gist.github.com/svyatogor/7839d00303998a9fa37eb48494dd680f)

It should be doable to implement also reverse way, but I don't currently have neither time nor device to test it.... ;-o

**Comment by litinoveweedle** [comment]
Closing as currently out of scope. If someone would find a way how to convert codes format on the fly I would gladly implement it. Having one format would benefit users significantly.
