### ISSUE TITLE
Device data file is missing 'temperatureUnit' key, using 'C' as default.

### ISSUE THREAD

**Issue by zslibra** [litinoveweedle/SmartIR#41]
Hello,
I installed smartir and seems to be working fine, but the logging has the following warning message Device data file is missing 'temperatureUnit' key, using 'C' as default.
May I know how to fix it？
Thanks.

**Home Assistant version**
2024.6.4

**SmartIR version**
1.17.16

climate:
  - platform: smartir
    name: climate_bedroom1
    unique_id: bedroom1_ac
    device_code: 9999
    controller_data:  remote.zhu_wo_hong_wai_yao_kong_qi
    temperature_sensor: sensor.kong_qi_jing_hua_qi_temperature
    humidity_sensor: sensor.kong_qi_jing_hua_qi_humidity

homeassistant log warning:
2024-06-22 15:08:48.839 WARNING (MainThread) [custom_components.smartir.climate] Device data file is missing 'temperatureUnit' key, using 'C' as default.
2024-06-22 15:08:48.841 WARNING (MainThread) [custom_components.smartir.climate] Device data file is missing 'temperatureUnit' key, using 'C' as default.

**Comment by litinoveweedle** [comment]
Hello,
the message means what the message says. Consult default device files to see what you need to add ('temperatureUnit'). I have task to document structure of the device files, but hadn't had time to do it yet.

**Comment by zslibra** [comment]
Thanks for your quick response.
Added temperatureUnit to my custom_codes then restart HA。
The warning message disappeared.
Thank you very much!
