### ISSUE TITLE
[Feature request] Add Swing mode toggle

### ISSUE THREAD

**Issue by boardlord1** [litinoveweedle/SmartIR#42]
My AC's Swing mode is a simple toggle - send an IR code to swing the flaps, and by sending the same IR code it stops swinging the flap stays in the new position (many basic ACs work the same way).

Would it be possible to add a simple Swing mode (toggle it on-off)? Thanks!

According to HA docs, the climate entity has this variety (swing_off and swing_on): https://developers.home-assistant.io/docs/core/entity/climate#swing-modes

Edit: there was a request for SmartIR back in 2021, but nothing happened: https://github.com/smartHomeHub/SmartIR/issues/746

**Comment by litinoveweedle** [comment]
Hello,I will need detailed explanation what exactly you would like to do, and what do you expect from it, step by step. i.E.. I want  to open HA, see my climate card, have swing switch there, click on it, it shall do this or that... etc.

But if I understand you correctly so far:
You can define freely any swing mode, (that means you can make two swing modes called "on" and "off") and assign to those any IR command you like (this means those can contain even same IR command) BUT as any other SmartIR climate command, those commands are expected to contain bits for switching the unit on, selecting given AC mode and setting temperature etc. This is the way which is used by most of HVAC units - all the current AC setting are always transmitted within any command (except off I think).

To test this just press the swing button on your remote when unit is off. If it will not switch on, that this command is not something this integration could handle (it would be overkill to integrate all such custom features for all existing AC unit types, I need to keep this integration universal and versatile.) But you can implement any such dedicated command easy way by using custom on/off helper switch hooked to automation which would send your command using remote HA integration on each switch change

**Comment by boardlord1** [comment]
My unit is like most - the commands contain all info: mode, temp. And the swing IR code only works when the unit is already on, it doesn't do anything when I press the swing button on the remote while it's off.

So the swing code is just for toggling swing on/off, with no additional info being sent, and only works when the AC is on.

Shame... I of course could cobble together a horizontal stack of the climate card and a button that sends the swing IR code, but it'd look a but clunky. I hoped to have this in the climate card itself. Thanks anyway!

**Comment by litinoveweedle** [comment]
Thank you for explanation. Then it is as I was afraid. such custom commands are really outside of the current scope. You are free to fork and modify the code as you like, if you will come with any KISS (Keep It Simple Stupid), you can propose PR. But for now I am afraid I can't think of any.

**Comment by boardlord1** [comment]
Looking through the open PRs of the original SmartIR repo, I came across this, seems to be of a similar logic? https://github.com/smartHomeHub/SmartIR/pull/995

**Comment by litinoveweedle** [comment]
Ok, I will check this, but no promises. ;-)

**Comment by boardlord1** [comment]
That's all I can ask for 🙂
