### ISSUE TITLE
If somebody wants to learn broadlink codes

### ISSUE THREAD

**Issue by vednolacni** [litinoveweedle/SmartIR#79]
Hopefully this can help people learn codes for Broadlink devices, and save people the time that I wish I had back.

Use your Broadlink RM4 Pro and RM4 Mini to easily learn codes to control Climate, Fan and Media devices. Easily be walked through the process of learning each of the codes, while getting a json output that is compatible with SmartIR & Home Assistant

[https://github.com/ericellb/Broadlink-CLI-SmartIR](https://github.com/ericellb/Broadlink-CLI-SmartIR)

**Comment by litinoveweedle** [comment]
Hello, thanks for contribution. I will probably need to create documentation page about how to create/update device codes files so I will definitely update it with the provided link.

**Comment by litinoveweedle** [comment]
OK, I check this tool but it is not compatible with the new incoming climate commands file structure - as it supports presetModes and also has implemented catch all modes/temperatures keys and modes failovers. Maybe if someone will fork and add those functions....

**Comment by ajayramaswamy** [comment]
I have made a try here 
https://github.com/ericellb/Broadlink-CLI-SmartIR/pull/7
