### ISSUE TITLE
Caveats about using this repo instead of the the smartHomeHub one

### ISSUE THREAD

**Issue by LastStarDust** [litinoveweedle/SmartIR#80]
Hello,

I recently came across this fork and am contemplating using it in place of the smartHomeHub version. The main reason is the growing list of open issues and pull requests (including mine) in that repository, which is becoming somewhat comical.

I would like to inquire about any considerations or potential drawbacks of using this fork. Additionally, could you please clarify your policy regarding pull requests opened in the smartHomeHub repository that could also apply to this one?

Thank you and keep up the excellent work.

Best regards,
Giorgio

**Comment by litinoveweedle** [comment]
Hi,
I am sorry I do not provide support to users, but I welcome contribution if you like to improve docs. You can test and play with the installation and read release notes to get what breaking changes could be and then propose to summarize them in the document update PR.

Regarding your existing PR - you can discuss with me what this is about and if suitable in the strategy of this fork then I would consider to accept it.

**Comment by LastStarDust** [comment]
@litinoveweedle  Sorry for being too vague, I was not worried about user support or my PR.
My question is: what is your policy for including upstream changes and PR into this project?

**Comment by litinoveweedle** [comment]
Hello, no problem. First if you compare changes from the original SmartIR with my repo and state of that project, I am not sure, that it can be still marked as upstream.

Second, I probably don't get your question right. Would you please explain what you would like to do in basic terms with the PRs in the original project? In addition I would also like to know why you are asking. Thanks.

**Comment by LastStarDust** [comment]
My question is:

What happens in this repository when there are some changes to the original repository?
1. Nothing happens
2. You apply the changes to this repository too

I am just asking out of curiosity.

**Comment by litinoveweedle** [comment]
I really do not understand your hypothetical questions. I will decide how I seem to fit the best purpose of this repo. That decision would be based on many factors, which I am neither able nor willing to predict now. I do not see any benefit in discussing this topic further. Thank you for your understanding.
