### ISSUE TITLE
HA error 

### ISSUE THREAD

**Issue by vednolacni** [litinoveweedle/SmartIR#81]
All of a sudden, I'm receiving this error:
![slika](https://github.com/user-attachments/assets/31a4a2a3-2d6a-4475-8a37-f2b89ab205d0)

This is my yaml for smartir:
![slika](https://github.com/user-attachments/assets/7df3cd74-b3b5-48e4-8071-14124069bc8f)

**Comment by litinoveweedle** [comment]
Read the docs and follow them. Your config is wrong follow config examples on the site.
