### ISSUE TITLE
power_sensor_delay issue?

### ISSUE THREAD

**Issue by rmxs** [litinoveweedle/SmartIR#82]
Hello, 

im using the following configuration but looks like power_sensor_delay  doesnt work.
I have set the power_sensor_delay  to 600 so that mean if the power sensor is off or on for 600+ secs it will send off or on commands.  The issue is that the commands are send after some seconds but sure not after 600 secs.

**Home Assistant version** Latest

**SmartIR version** Latest

**SmartIR configuration**
  - platform: smartir
    name: AC Livingroom
    unique_id: ac_livingroom
    device_code: 1070
    controller_data: remote.smart_ir1
    temperature_sensor: sensor.thermometro_kouzina_temperature
    humidity_sensor: sensor.thermometro_kouzina_humidity
    power_sensor: sensor.ac_living_room_status
    power_sensor_delay: 600
    power_sensor_restore_state: true

**Comment by litinoveweedle** [comment]
As you decided to ignore all the required inputs for any new issue (see the template) which I need to try to troubleshoot any issue, I decided to close it.
