### ISSUE TITLE
Adding Multiple Climate devices

### ISSUE THREAD

**Issue by hazell20** [litinoveweedle/SmartIR#93]
hi mate

i have two aircon units that are identical and I am trying to add both of them and can only get one unit to work I have been trying add unit multiple times and does not seem to be working both codes work separately but when I paste both in like that only second unit works

from my config file 

climate:
    
    platform: smartir
    name: Rhys Aircon
    unique_id: rhys_ac
    device_code: 1400
    controller_data: remote.rhys_ir
    temperature_sensor: sensor.0x286d9700010362d6_temperature
    humidity_sensor: sensor.loung_room_temp_humidity
    
    platform: smartir
    name: Kathryn Aircon
    unique_id: Kathryn_ac
    device_code: 1400
    controller_data: remote.broadlink_remote
    temperature_sensor: sensor.loung_room_temp_temperature
    humidity_sensor: sensor.loung_room_temp_humidity

cant find a log to submit

**Comment by litinoveweedle** [comment]
Closing issues as invalid as disregarding issue policy:
- no debug log was provided
- no detailed description of the fault and/or expected behavior provided.

**Comment by hazell20** [comment]
Hi Mate

The Device shows up as This entity is no longer being provided by the smartir integration. If the entity is no longer in use, delete it in settings. so second device is not working where are your logs located then. when I add both device in config.yaml only one device is active if I cut out working device out off the config.yaml file the other device starts working

**Comment by litinoveweedle** [comment]
1. Enable SmartIR debug log level as show int he issue template
2. Restart HA
3. Attach HA logs to this issue.

Those log should contains also logs from the registrations of the entity which should be helpful to analyze issue. If you submit those I would reopen issue. Otherwise it will stay closed - it is up to you.

**Comment by hazell20** [comment]
I have sorted it thanks anyway mate
