### ISSUE TITLE
Invalid climate device JSON file when IR-code is reused

### ISSUE THREAD

**Issue by ehedlund76** [litinoveweedle/SmartIR#94]
When debugging I've found log traces stating that the climate device file is invalid because of reused IR-codes. In my opinion the file is valid. The reason why IR-codes are reused in my case is because HVAC mode fan_only use the same code for all temperatures since different temperature has no meaning for fan_only.

This issue is no big deal.

**Comment by litinoveweedle** [comment]
Hello,

this is correct behavior, as with new extended format of the  climate files it is suggested to use `-` as single key for temperature in such case. Please check [docs](https://github.com/litinoveweedle/SmartIR/blob/master/docs/CODES_SYNTAX.md)

**Comment by litinoveweedle** [comment]
Please would you be so kind to check [docs](https://github.com/litinoveweedle/SmartIR/blob/master/docs/CODES_SYNTAX.md) and propose potential improvements to be more comprehensive and easier to understand? There is always issue if docs are written by developer. :-)

**Comment by ehedlund76** [comment]
Hi @litinoveweedle 
I'll have a look and get back to you soon.

**Comment by ehedlund76** [comment]
Hi,

I've read the code syntax documentation. I find it pretty clear. The catch all is super. I didn't get it before I read the docs. 

So, my comments are only minor:
1. Structure example
Since the off-command deviates from the rest of the structure, I suggest to add the off command and place it first to make it clear
2. Mandatory levels?
I guess some of the levels in the hierarchy are mandatory, for instance operation mode and fan mode. Can't just skip what you like :-) I suggest to make that clear somehow, for instance parenthesis on levels that are optional, or be explicit on the levels that must be present
3. Duplicate IR commands
From my understanding the third possibility (iii.) tells me that its valid to duplicate IR commands for instance for fan_only operation. This will result in the warning about invalid climate device file. The warning in the log will probably get some of us a bit confused :-)

**Comment by litinoveweedle** [comment]
thank you for your help and suggestions:

1. I will definitely do it, as I miss document the 'simple' command (on, off etc). I will update commands section
2. Actually only operation mode is really required now. All other modes are optional. But yes, I will explicitly mentioned that.
3. Yes, you are correct, but I don't like that approach (duplicates of the same command) at all. It is there mostly for backward compatibility. I would prefer users to migrate to other styles if possible. I am not yet fully decided how to handle this. What do you think?

**Comment by litinoveweedle** [comment]
Proposed modifications were added as #95 and merged into master.
